### ISSUE TITLE
True anomaly angle is shown in radians

### ISSUE THREAD

**Issue by qsantos** [CYBUTEK/KerbalEngineer#104]
Although the symbol for degrees `°` is displayed, the value in the orbital panel for the true anomaly is given in radians.

It also seems like angle to AN and angle to DN are using the sum of a value in degrees and a value in radians.

**Comment by Gerry1135** [comment]
This was fixed in PR #100

**Comment by qsantos** [comment]
Oh, I must have missed it. Sorry for the inconvenience.
