### ISSUE TITLE
KER KIS unintended interaction

### ISSUE THREAD

**Issue by tedingus72** [CYBUTEK/KerbalEngineer#112]
When only having KER 1.1.2.2 and KIS 1.3.0 I am experiencing closing inventory windows when I mouse out of the KER window in the VAB.  

To recreate this have stock KSP and install the KER and KIS mods.  Start a new game save and open the VAB.  Pick any KIS storage module, in this case I picked the Mk2 command module.  If it is not open, then open the KER window showing the staging DV.  Right click on the command module and open seat 0 inventory.  Move your mouse into the KER window and then move it back out and it closes the KIS inventory window.

Attached is my KER.log and KSP.log files
[KER-KIS.zip](https://github.com/CYBUTEK/KerbalEngineer/files/552242/KER-KIS.zip)

**Comment by arekbulski** [comment]
Could you record a short video showing it? Can record using Fraps and post on youtube/etc. 
I would need to see what is wrong, like in functionality, not error logs.

**Comment by tedingus72** [comment]
Well apparently since it has been over a year since I reported this it has been fixed.

**Comment by tedingus72** [comment]
This was an issue over a year ago.  Latest tests do not have this issue so
they may have fixed it in 1.3.  I believe some of the original messages I
had with one of the authors at the time pointed this to an issue in how
unity handled things in 1.2.2.
