### ISSUE TITLE
engineer is contributing to physics/drag?

### ISSUE THREAD

**Issue by fommil** [CYBUTEK/KerbalEngineer#115]
I have a very simple stock rocket design for rescuing kerbals in low Kerbin orbit (cheapest I could come up with after many iterations... this is a great way to get Kerbalnauts!). But if I add the engineer to the pod, the rocket doesn't take off straight.

Is this expected? I am happy to share my rocket design, see https://gist.github.com/fommil/9f441194dc4d4c5ba1bffc342e8365f0

**Comment by arekbulski** [comment]
I dont see the KER chip in that craft. Can you link me CFG file for KER chip where its mass and drag parameters are defined?

**Comment by fommil** [comment]
sorry it's been so long since I reported this that I'm not sure if its still a problem. I'll close.
