### ISSUE TITLE
Infinite loop in CalcInterceptAngle / AngleHelper.Clamp360

### ISSUE THREAD

**Issue by jd284** [CYBUTEK/KerbalEngineer#126]
This appears to be the cause of a long-standing issue with KerbalEngineer locking up the game when a ground base is targetted with the rendezvous window open.

It's extremely difficult to reproduce, happens for me every couple of weeks only. After adding a bunch of debug print statements I finally narrowed it down to an infinite loop in AngleHelper.Clamp360, which happens when it is called with an argument of Infinity by CalcInterceptAngle in the RendezvousProcessor. Of course adding or subtracting from infinity makes no difference whatsoever so the while loops never terminate.

So to fix it, a couple of solutions come to mind:
- Handle it in Clamp360 and return a sensible value (although it's not obvious what a sensible value would be... the same infinity? zero?)
- Change CalcInterceptAngle to not call Clamp360 if the argument would be an infinity. Same question what it should return then...
- Change CalcInterceptAngle and fix the calculation so it doesn't return infinity.
- Don't call CalcInterceptAngle for landed vessels, it doesn't make much sense.

I haven't been able to reproduce the problem since narrowing it down, so I can't say yet exactly why the angle is infinite. I'll post more if I find out.

**Comment by jd284** [comment]
Huh, just after I gave up on reproducing it, there it was again.

So it turns out that targetRadius is zero, hence the argument to Math.Pow has a division by zero.

**Comment by FatHand** [comment]
Can confirm experiencing this on Mac, KSP 1.2.2.

Orbiting Mun. No target selected. Opened Rendezvous window and began search for a Mun base. Clicked search result and the game froze.

Had recently passed over the base at about 20km altitude. Not sure what the vessel unpack range is and if that would make any difference.

**Comment by CYBUTEK** [comment]
The AngleHelper clamps now check for NaN and Infinity before processing in bde5d1d3c9e82bad50711b1319e5ba39f0a4c891, this should resolve the issue.
