### ISSUE TITLE
KSP 1.3 crash with KER 1.1.2.8

### ISSUE THREAD

**Issue by gilad-teller** [CYBUTEK/KerbalEngineer#127]
Tested with KER as the only installed mod. Attached crash report.
[2017-05-26_122926.zip](https://github.com/CYBUTEK/KerbalEngineer/files/1031419/2017-05-26_122926.zip)

**Comment by Gerry1135** [comment]
Have you tried the version I posted a while ago for 1.2.9?

http://forum.kerbalspaceprogram.com/index.php?/topic/17833-121-kerbal-engineer-redux-1128-2016-12-02/&do=findComment&comment=3024393

**Comment by gilad-teller** [comment]
Thanks, I can confirm this is working,
