### ISSUE TITLE
Enhancement: Possibility to show altitude over ground

### ISSUE THREAD

**Issue by rbjorklin** [CYBUTEK/KerbalEngineer#130]
It would be really handy if the altitude over ground could be calculated and shown in KER. This would be especially useful when flying Space Planes in map mode where altitude is completely missing.

**Comment by CYBUTEK** [comment]
It is and it's the called the "Altitude (Terrain)" readout.

**Comment by rbjorklin** [comment]
Sorry I must have missed it somehow. Thanks for providing a great plugin! :)
