### ISSUE TITLE
Kerbal engineer spam with editor extentions v2.5

### ISSUE THREAD

**Issue by Joshwoo69** [CYBUTEK/KerbalEngineer#15]
spams
[Log]: KerbalEngineer -> 2001413032

**Comment by mythbusters844** [comment]
I am also getting this log spam with Editor Extensions 2.5 but it only happens when I place the RCS-powered OMS engine on a rocket. It seems to continue spamming in-flight too.

**Comment by Joshwoo69** [comment]
Yes same with mythbusters
*side note o/ mythbusters*

**Comment by mdkendall** [comment]
I am also seeing this error spammed into my log during flight. I only see it happening on one particular vessel, and the notable thing about that vessel is that it has O-10 mono-propellant engines (part name omsEngine). I note that 2001413032 seems to be an identifier for the MonoPropellant resource.

KSP 0.90. Mods installed are KER, Kerbal Alarm Clock, Docking Alignment Port Indicator and Procedural Fairings.

**Comment by mdkendall** [comment]
Further info:
http://forum.kerbalspaceprogram.com/threads/18230?p=1664239#post1664239
