### ISSUE TITLE
how to build this project?

### ISSUE THREAD

**Issue by calanchue** [CYBUTEK/KerbalEngineer#153]
There are some GUI issue(https://github.com/CYBUTEK/KerbalEngineer/issues/146) for some language users. it is related to xml encoding problem, so if i can build project, solution for the problem will be clear. I want to solve this problem myself. I have encountered some error while building. 

My process
1. import project from unity to create KerbalEngineer.Editor
2. add reference to UnityEngine.dll, UnityEngine.UI.dll, Assembly-Csharp.dll, Assembly-Csharp-firstpass.dll in 
ksp folder. 
3. ERROR !!
![image](https://user-images.githubusercontent.com/1866710/38451496-de00927c-3a6b-11e8-97c3-4fe13a0e2a21.png)

Project request me to include TrackingStation and SectionModuleTS. But where can i find them? What file should i reference?

Thank you for advance

**Comment by jrbudda** [comment]
Uhh those are files from my repository.

**Comment by calanchue** [comment]
Oh, Sorry for wrong thread. Weird thing is that, I have cloned your(@jrbudda) repository, but it caused a issue. Dose it needs other repository to build it? 
Anyway it's not relevant to here, i will close issue
