### ISSUE TITLE
ADDON BINDER: Cannot resolve assembly

### ISSUE THREAD

**Issue by Krazy0** [CYBUTEK/KerbalEngineer#156]
[KSP.log](https://github.com/CYBUTEK/KerbalEngineer/files/5614139/KSP.log)
I am getting this error message immediately at KSP launch, before the main menu. Same as below from KSP forum. 
Running KER 1.1.7.2 with KSP 1.10.1 on Win 10. Log attached.

_On 11/15/2019 at 5:11 PM, linuxgurugamer said:
KER 1.1.7.1, in a 1.8.1 game

Getting the following errors:

ADDON BINDER: Cannot resolve assembly: KerbalEngineer.Unity, Culture=neutral, PublicKeyToken=null
 
ADDON BINDER: Cannot resolve assembly: KerbalEngineer.Unity, Culture=neutral, PublicKeyToken=null
Quick n dirty solution is to rename the KerbalEngineer.Unity.dll to +KerbalEngineer.Unity.dll

Better solution is to add the following to the AssemblyInfo.cs:

[assembly: KSPAssemblyDependency("KerbalEngineer.Unity", 1, 0)]_

**Comment by TinyBigJacko** [comment]
Noticed the same error in my log yesterday when debugging a totally different issue (related to MechJeb2 and ModuleManager, as it goes, but still this is worth fixing in KER, imho).

Same set of kit: (WindowsPlayer x64) en-us and KER 1.1.7.2

line 36 & 38 of log:

[ERR 17:15:44.746] ADDON BINDER: Cannot resolve assembly: KerbalEngineer.Unity, Culture=neutral, PublicKeyToken=null

[ERR 17:15:44.746] ADDON BINDER: Cannot resolve assembly: KerbalEngineer.Unity, Culture=neutral, PublicKeyToken=null
[KSP.zip](https://github.com/CYBUTEK/KerbalEngineer/files/5622505/KSP.zip) (sorry 'bout the zip; wouldn't let me upload the raw .log file for some reason).

**Comment by Krazy0** [comment]
reference to original post: 
https://github.com/jrbudda/KerbalEngineer/issues/52

Open over a year now...

**Comment by Krazy0** [comment]
Error resolved in KER 1.1.8.3
