### ISSUE TITLE
Resource Mass Sometimes Misreported

### ISSUE THREAD

**Issue by toadicus** [CYBUTEK/KerbalEngineer#20]
In some situations, the resourceMass and totalResourceMass values I'm fetching from KER do not seem to make sense.  Using the Kerbal X as an example; here's a readout of the stages in the editor:

![Stages In Editor](http://ksp.hawkbats.com/dev/pics/KerbalX00-In_Editor.png)

"Mass" and "Total Mass" are fetched directly from Stage.mass and Stage.totalMass.  Here's my vessel info panel on the pad before staging at all:

![Stages In Editor](http://ksp.hawkbats.com/dev/pics/KerbalX01-On_Pad.png)

The slight difference in total mass is the fault of another mod of mine, but is consistent.  However, the reported Resource Mass of 145 tons is necessarily incorrect.  "Resource Mass (stage)" is Stage.resourceMass and "Resource Mass" is Stage.totalResourceMass.

Here's the panel again after releasing the launch clamps (so we've staged twice):

![Stages In Editor](http://ksp.hawkbats.com/dev/pics/KerbalX02-Post_Launch.png)

The fuel mass in two nacelles is 400 * 3 * 2 * .005 = 12 kg.  In all 6 nacelles it's 36 kg.  There's another 48 kg in the center stack.  None of those values or any reasonable sum seem to be represented here.  Also, the 25.806 value does not change as fuel burns.

When the first pair of nacelles runs out of fuel, but before they're decoupled, the readouts change:

![Stages In Editor](http://ksp.hawkbats.com/dev/pics/KerbalX03-First_Nacelles_Empty.png)

Again, both resource values reported much be incorrect, as they are equal to or greater than the total craft mass.

When the first pair of nacelles are decoupled (so we've staged one more time), it changes again:

![Stages In Editor](http://ksp.hawkbats.com/dev/pics/KerbalX04-First_Nacelles_Decoupled.png)

As a temporary workaround, I have hacked access to baseMass at the stage level [into my local fork](http://git.toad.homelinux.net/projects/VesselSimulator.git/commitdiff/745067b).

Let me know how I can help!

**Comment by Gerry1135** [comment]
I believe the fix for this is to change this line in simulation.cs:

stage.resourceMass = this.stepStartMass - this.stepEndMass;

to:

stage.resourceMass = this.stageStartMass - this.stepEndMass;

Toadicus is going to try this and let us know.

**Comment by toadicus** [comment]
That does appear to fix it.  Thanks!
