### ISSUE TITLE
[Feature Request] Atmospheric button in Compact View

### ISSUE THREAD

**Issue by BevoLJ** [CYBUTEK/KerbalEngineer#21]
Was wondering if it might be at all possible to add an atmospheric toggle in the VAB gui's Compact View.

**Comment by Gerry1135** [comment]
I have implemented this in PR #29

**Comment by BevoLJ** [comment]
That would rock.  Thanks.  :)

**Comment by CYBUTEK** [comment]
#29 has been merged.
