### ISSUE TITLE
Version 1.0.15.0 doesn't actually include the latest fixes

### ISSUE THREAD

**Issue by Gerry1135** [CYBUTEK/KerbalEngineer#23]
I have examined the release DLL with ILSpy and the resource type logging is still there and the KIDS support isn't so I guess you did something silly when building the release.

**Comment by CYBUTEK** [comment]
In the haste to get it all complete in my spare time between commercial projects, I did do something silly.  Just awaiting curseforge approval for the new build.

**Comment by CYBUTEK** [comment]
All fixed, and including https://github.com/CYBUTEK/KerbalEngineer/pull/22
