### ISSUE TITLE
Incorrect latitude directional in first degree south

### ISSUE THREAD

**Issue by Euryleia** [CYBUTEK/KerbalEngineer#28]
When displaying latitude on a HUD, KER displays all coordinates from 0°0'1" S to 0°59'59" S incorrectly as "N" instead of "S".  Basically everything north of 1° S is displayed as N.

**Comment by CYBUTEK** [comment]
That's how KSP is handing out the information.  In this case KER isn't modifying it in any way.

**Comment by Euryleia** [comment]
Yeah, it looks like FlightGlobals.ship_latitude is correct, but KSPUtil.PrintLatitude is buggy.  Some other mods use different functions to convert it to a string correctly (e.g. MechJeb2 uses Coordinates.toStringDMS, which presumably stands for Degrees/Minutes/Seconds).

**Comment by Gerry1135** [comment]
I have fixed this in PR #29

**Comment by CYBUTEK** [comment]
#29 has been merged.
