### ISSUE TITLE
Incorrect TWR in VAB using new FAR

### ISSUE THREAD

**Issue by Dragnmn** [CYBUTEK/KerbalEngineer#31]
There is a discrepancy in TWRs between the VAB and launch when using the new FAR v0.15. The TWR shown in the VAB is higher than on the launchpad, and the latter is correct.

It seemed more like a KER bug than a FAR bug, so I report it here. If it's not I will report it in the FAR repository.

![2015-05-09_00001](https://cloud.githubusercontent.com/assets/11380679/7551582/f1460dd2-f68d-11e4-8778-48133d00da23.jpg)
![2015-05-09_00002](https://cloud.githubusercontent.com/assets/11380679/7551581/f1455d7e-f68d-11e4-980e-1df00b989c24.jpg)

**Comment by CYBUTEK** [comment]
Turn on 'Atmospheric' mode in the VAB.
