### ISSUE TITLE
Move top-level directory into GameData/ and rename CHANGES.txt

### ISSUE THREAD

**Issue by mathuin** [CYBUTEK/KerbalEngineer#40]
Many mods are built such that they can be unzipped from the top level with files falling where they should in GameData/.  This is a big help when attempting to maintain mod configuration with updates.

Similarly, many mods provide CHANGES.txt or README.txt which are beneficial to users.  Unfortunately, leaving these files with generic names in the top directory leaves them prone to being overwritten.

It would be nice if KerbalEngineer/ was under GameData/ in the zip, and also if CHANGES.txt were renamed to GameData/KerbalEngineer/CHANGES.txt or GameData/KerbalEngineer-CHANGES.txt or something of that sort.

Thanks!

**Comment by Katalliaan** [comment]
Took me a moment to understand what you were saying. Just to clarify: you're talking about restructuring the .zip so that it's all contained inside a GameData folder, then all Engineer-related files be in the GameData/KerbalEngineer folder?

**Comment by mathuin** [comment]
Yes, that's it.  The goal being that I can unzip the .zip from the game installation directory and all the content will go where it belongs.  Sorry I wasn't clear. :-)

**Comment by mathuin** [comment]
CKAN does a great job installing KER without this change, so I'm going to close this issue.
