### ISSUE TITLE
Feature Request: Maneuver node Ap and Pe elements

### ISSUE THREAD

**Issue by PEmergence** [CYBUTEK/KerbalEngineer#48]
I use a custom HUD with KERs excellent Time to burn, Burn dV and Burn time parked next to the stock maneuver node dV display. It would be excellent to be able to add the node's projected Ap and Pe to this area. Would save a lot of the nonsense of trying to click on the stock markers to display the values and keep at the things I care about when dragging out a node in one place.

**Comment by Gerry1135** [comment]
Handy suggestion.  Implemented in PR #47

**Comment by PEmergence** [comment]
Great! Look forward to the release.

**Comment by CYBUTEK** [comment]
This was merged with PR https://github.com/CYBUTEK/KerbalEngineer/pull/47
