### ISSUE TITLE
The Vessel Name readout

### ISSUE THREAD

**Issue by legolegs** [CYBUTEK/KerbalEngineer#53]
I want my vessel name on the screen (using those nice backgroundless windows) for two reasons:
1) I always forget to rename ship according to its current mission or success state ("Moho Flybyer" => "Moho Impactor")
2) I want the vessel name to be left on screenshots
Can we please have it? This should not be difficult to do.

**Comment by Gerry1135** [comment]
Yes, this should be very easy to add and would be quite useful. I am away from home at the moment but I'll try to add this sometime soon if no one else has first.
