### ISSUE TITLE
Framerate drops when escaping the sun with time to apoapsis readout active

### ISSUE THREAD

**Issue by fat-lobyte** [CYBUTEK/KerbalEngineer#55]
Hi! I just noticed that Kerbal Engineer causes a massive framerate drop (to about 0.2 fps), when the ship is on escape Trajectory out of the sun, while showing time to apoapsis/periapsis data.

Disabling the all sections with the time to Periapsis/Apoapsis readout fixes the Framerate, enabling it causes it to drop again.

**Comment by Gerry1135** [comment]
This is a bit weird because the time to Ap readout is not calculated by KER, it is read directly from the vessel's orbit object.  However, I'll investigate to locate the precise cause of the slowdown (assuming I can repeat it) and devise a workaround.

**Comment by antplant** [comment]
Could be a red herring if there are other readouts in the same section(s) causing the problem?

**Comment by antplant** [comment]
Actually, this is probably caused by the time formatting which is currently very inefficient (iterating every second in order to format the time as a string). Luckily this has already been addressed: https://github.com/CYBUTEK/KerbalEngineer/pull/59

**Comment by Gerry1135** [comment]
Yep, you could well be correct there.

**Comment by CYBUTEK** [comment]
b32b58cdb1deb5ecf75fbd42ee0835ccf044e56e fixes this issue, thank you :)
