### ISSUE TITLE
x offset option for engineer overlay bottom pop-ups

### ISSUE THREAD

**Issue by Gaiiden** [CYBUTEK/KerbalEngineer#56]
I'd rather have them more in the middle since I have blizzy's bar on the left and the app launcher on the right. This doesn't have to be exposed in the GUI I wouldn't mind just editing the xml files

**Comment by CYBUTEK** [comment]
This feature is already implemented (although not GUI exposed) and is adjustable in the 'KerbalEngineer/Settings/BuildOverlay.xml' file.

  <SettingItem>
    <Name>vesselWindowX</Name>
    <Value xsi:type="float">330</Value>
  </SettingItem>

The resources pop-up position is linked to the position + width of the vessel's.
