### ISSUE TITLE
Allow rebinding of backslash shortcut

### ISSUE THREAD

**Issue by aubade** [CYBUTEK/KerbalEngineer#62]
I'm a left-handed user, and I like being able to use the backslash key in my vessel controls, but currently it doesn't seem that there's any way to get KER not to use it for its show-hide button. Is there any chance we could get an option in the config UI to change the key KER uses?

**Comment by CYBUTEK** [comment]
Key bindings editor has been implemented and is accessible under 'Settings' in the Build Engineer.
