### ISSUE TITLE
Variable Name issue

### ISSUE THREAD

**Issue by Praisebetoscience** [CYBUTEK/KerbalEngineer#64]
Made an inline comment here: 

https://github.com/CYBUTEK/KerbalEngineer/commit/ca5ea418be929d986b7716541e656bc957c3c9dd

Not a C# programmer, but I believe it's case sensitive.  If I'm wrong, just ignore.

**Comment by CYBUTEK** [comment]
It is indeed case sensitive and a little typo within Squad's code.  Changing it in KER will render the project non-compilable.  Nice catch though :)

**Comment by CYBUTEK** [comment]
Update: Logged the typo on Squad's bug tracker.
