### ISSUE TITLE
Log spam problem with 1.0.19.1 and ProceduralParts 1.1.8

### ISSUE THREAD

**Issue by RealKolago** [CYBUTEK/KerbalEngineer#65]
With a vanilla KSP and only KerbalEngineer 1.0.19.1 and ProceduralParts 1.1.8 installed the log gets flooded with "stdCost: 0" entrys.

**Comment by Gerry1135** [comment]
I can't find that message anywhere in the KER source so I presume it is either coming from Procedural Parts or is coming from the core game when handling parts that use the IPartCostModifier interface.

**Comment by RealKolago** [comment]
So whats next? Open an Issue at ProceduralParts?

**Comment by Gerry1135** [comment]
This was a problem with Procedural Parts that has since been resolved so this can be closed.
http://forum.kerbalspaceprogram.com/index.php?/topic/96402-105-procedural-parts-parts-the-way-you-want-em-v1111-dec-16/&do=findComment&comment=2296292

**Comment by arekbulski** [comment]
How about closing this thread? Its already fixed.
