### ISSUE TITLE
Enable radially attached parts to cross-feed.

### ISSUE THREAD

**Issue by CYBUTEK** [CYBUTEK/KerbalEngineer#67]
Some wings such as the delta wing can contain fuel.  When attached radially to a fuselage they cross-feed, but this is not taken into account and fuel lines must be used for correct dV calculations.

**Comment by Gerry1135** [comment]
Yes, there have been a couple of changes to the existing stack search mode and also some new modes implemented that the simulation code doesn't handle correctly. In theory it is a matter of disabling one of the rules and adding one or two crossfeed checks but I've not yet had the time to sort it out.
