### ISSUE TITLE
Officially release to support version 1.0.5

### ISSUE THREAD

**Issue by jlegs** [CYBUTEK/KerbalEngineer#69]
I'm just filing a ticket to see if we can get the Curse link officiall updated to the version for KSP 1.0.5

**Comment by BadRAM** [comment]
also ckan 1.0.5 support would be nice, as it wont let you install through it if it detects a version mismatch.

**Comment by alex88** [comment]
In the meantime how can I install this for 1.0.5? Just download the whole folder and unpack?

**Comment by jescholl** [comment]
Just copy the `output/KerbalEngineer` directory to your `GameData` directory.

**Comment by alex88** [comment]
@jescholl thanks that worked fine!

**Comment by taori** [comment]
any particular reason why this is not pushed to be supported by ckan? Kerbal Engineer has always been the number 1 addon which i would not want to play ksp without. i am willing to contribute if it's a matter of workload (meanwhile i'll just do a manual install though)

**Comment by antonytrupe** [comment]
This is done now, no?

**Comment by CYBUTEK** [comment]
Indeed it is :)
