### ISSUE TITLE
Ignore massless propellants within the fuel flow simulation.

### ISSUE THREAD

**Issue by CYBUTEK** [CYBUTEK/KerbalEngineer#75]
Asked for by MatterBeam on the forum: http://forum.kerbalspaceprogram.com/index.php?/topic/17833-105-kerbal-engineer-redux-v10194/&page=110#comment-2406422

**Comment by Gerry1135** [comment]
Are they just referring to this:

2947b76bb8ac6d85b6d1a10e8701b63a7a89d0e3

...or something different?

**Comment by CYBUTEK** [comment]
Just that :P

Thanks for finding it :)
