### ISSUE TITLE
TWR and dV read 0.0 in 1.1.0.0

### ISSUE THREAD

**Issue by Corbald** [CYBUTEK/KerbalEngineer#78]
As stated. New career game, new craft. KER is only mod. Applies to all modes (partless/career/pilot/tracking) regardless of toggle state.

**Comment by Corbald** [comment]
It would appear that this is related to a bug in the Beta of KSP itself. The Engineer's Report is reading that the engine will be discarded before it can be used, which is NOT true, as the craft is staged properly. Adding a blank stage anywhere above the engine seems to resolve this issue, even if it's stage 0 (i.e. set to a blank stage after parachutes would deploy. KSP may be reading stages at -1 ?? so it might be reading that the decoupler in the NEXT stage would stage first, resulting in the engine never igniting??

**Comment by CYBUTEK** [comment]
Would this be related to the heat shield bug that has just been fixed?

Please download and replace your KerbalEngineer.dll file available here: https://github.com/CYBUTEK/KerbalEngineer/tree/master/Output/KerbalEngineer
and see if this fixes it.

**Comment by Corbald** [comment]
Yep, that did it. Closing!
