### ISSUE TITLE
1.1 pre release deltav not calculated after fairings

### ISSUE THREAD

**Issue by derdotte** [CYBUTEK/KerbalEngineer#79]
If you put a fairing in the staging menu as your first stage to be fired everything after that fairing is not being calculated in KER, works with inbetween too so if you jettison your fairing between stage 1 and 2 the second stage will have not stats readout (but works!).
https://www.dropbox.com/s/l96he046y5uzdwn/orbiter.craft?dl=0
my craft file (just a simple one but it shows the effect)

**Comment by CYBUTEK** [comment]
Can you confirm that this bug is only evident whilst in flight and not in the VAB/SPH?

**Comment by CYBUTEK** [comment]
Also found and fixed an issue with how fairing mass was being calculated. KSP no-longer includes fairing mass on the part, but only as queryable module mass.
