### ISSUE TITLE
Impact Biome broken

### ISSUE THREAD

**Issue by harryyoung** [CYBUTEK/KerbalEngineer#83]
The Impact Biome Readout seems confused. It correctly states that my current biome is the highlands, however the impact biome is projected to be in the water.

![2016-04-02 2](https://cloud.githubusercontent.com/assets/1156184/14228278/8c303d92-f910-11e5-9e78-fc74a3fc8d2f.png)

[impact-biome.zip](https://github.com/CYBUTEK/KerbalEngineer/files/200959/impact-biome.zip)

**Comment by Gerry1135** [comment]
This has been fixed in the experimental branch.  KSP 1.1 has changed the Orbit.trueAnomaly value from degrees to radians to require less angle conversions in some stock code.

**Comment by harryyoung** [comment]
fixed, closed
