### ISSUE TITLE
FPS Drop when opening Goo Container / Materials Bay / using Communotron

### ISSUE THREAD

**Issue by L33m4n123** [CYBUTEK/KerbalEngineer#87]
Hey,

I did some testing earlier. With the ship I attached (With a small one I could not replicate it) I get MASSIVE FPS drops if I use the GO Container, Materials Bay or transmit science via the Communotorn.
(Anywhere I tested it.. Launchpad.. Orbit.. Suborbital)

However if I remove the Part 
"Kerbal Enigneering System" (The green motherboardi thing) it works smoothly

I put it on the hatch of the commandpot so you can easily find it and test it out yourself

Tested in Version  KSP 64 bit v1.1.0.1203 on Windows 10 with Kerbal Engineer Redux v1.1.0.1

I add the .craft file AND the output log. Cheerio

[output_log.zip](https://github.com/CYBUTEK/KerbalEngineer/files/218008/output_log.zip)

[Duna Simulated.zip](https://github.com/CYBUTEK/KerbalEngineer/files/218009/Duna.Simulated.zip)

**Comment by Gerry1135** [comment]
This is almost certainly the same as #80 which has already been fixed for the next version.

**Comment by L33m4n123** [comment]
Oh yea. Looking at the log and the error he postet it's the same error. Sorry for the duplicate
