### ISSUE TITLE
NRE spam with KSP-pre 1209

### ISSUE THREAD

**Issue by symmeclept** [CYBUTEK/KerbalEngineer#89]
I believe there are changes to AppLauncher in 1209 that confound KER in the VAB/SPH.

From KSP.log:
`	KerbalEngineer.Editor.BuildAppLauncher.Update ()
[EXC 19:18:22.185] MethodAccessException: Method `KSP.UI.UIRadioButton:get_Button ()' is inaccessible from method `KerbalEngineer.AppLauncherButton:Disable ()'`

Ad infinitum...

[Log files](https://www.dropbox.com/s/ldrlnyfdee8epj2/output_log.zip?dl=0)

**Comment by Gerry1135** [comment]
This is already fixed in PR #88
