### ISSUE TITLE
IFS mass display glitch (KER 1.1.0.1)

### ISSUE THREAD

**Issue by cherrydev** [CYBUTEK/KerbalEngineer#90]
When using a tank modded by Interstellar Fuel Switch, the KER display (in the VAB) the mass displayed flickers between two values.  One is the correct value and the other is the correct value minus the empty weight of the tank.  I'm using Fuel Tanks Plus with the latest release of IFS 1.20 (the latest for KSP 1.1).

**Comment by cherrydev** [comment]
(Btw, also tried with Gerry1135's PR #88 patches, same problem).

**Comment by Gerry1135** [comment]
This appears to be a bug in IFS's implementation of IPartMassModifier

**Comment by cherrydev** [comment]
I might also point out that the built-in KSP craft report that displays the total weight of the craft does not do this.

**Comment by cherrydev** [comment]
Yup, IFS bug.  Thanks.
