### ISSUE TITLE
TWR incorrect in VAB

### ISSUE THREAD

**Issue by krenshala** [CYBUTEK/KerbalEngineer#92]
I've been noticing that the thrust to weight ratio (TWR) is about 25% lower on the launch pad than shown in the VAB (alternately viewed as the VAB is shown to be 33% higher). I first noticed the problem in 1.0.5, but I did some testing when 1.1 came out to determine the amount since I was only using KER and no other mods.

If the VAB engineering panel lists a TWR of 2.40 then you only have 2.0 on the launch pad.  This is as of KSP 1.1.1228 with KER 1.1.0.2.

Testing steps:

New career game.  Build a rocket that consists of: 

(1) Mk 1 command pod
(1) Mk 16 parachute (top of pod)
(1) ER-7500 (bottom of pod, clipped upward into it)
(1) RT-5 "Flea" SRB with the thrust limiter set to 29.5%

Then compare TWR settings in the VAB and the launch pad.  In the VAB is shows 2.40, while on the launch pad it shows 2.04.  Different TWRs yield the same change in ratio, with the actual flight scene registering 25% lower than when in the VAB.  I have *not* tested this in the SPH.

This difference in readings causes problems when setting up rockets with a TWR below 1.6 because on the pad they will be at or below 1.0 when you go to fly them (and how I discovered the problem - built a rocket that was only 1.3 due to career limitations and it fell over on the pad because it was only 0.96 TWR at "launch").

**Comment by Gerry1135** [comment]
This is almost certainly just the difference in Isp and thrust between vacuum and sea-level.  In the VAB just click the "Atmospheric" button in the KER window...

**Comment by krenshala** [comment]
That would make sense, and is something I didn't even think about checking.  This would also be much more noticable in 1.1 with its changes than in 1.0.5 and FAR where I first started wondering about it (but never was sure if it was me not building the rocket correctly or not).

I'll give that a check later tonight and will update if that is not the 'problem'.

**Comment by Gerry1135** [comment]
Can you close this issue if it isn't valid please?

**Comment by krenshala** [comment]
Apologies.  It was indeed the difference between ASL and vacuum Isp.
