### ISSUE TITLE
Files for configuration that are written to disk on every session should be stored in the "PluginData" directoy.

### ISSUE THREAD

**Issue by Galenmacil** [CYBUTEK/KerbalEngineer#98]
This is to avoid Module Manager rebuilding patches from scratch on every game loading instead of relying on it's the much faster cache. Please, read this for more detail:

https://github.com/m4v/RCSBuildAid/issues/32

**Comment by CYBUTEK** [comment]
KER saves its configuration data using its own XML serialisation. As far as I am aware Module Manager only builds patches from .cfg files that use the ConfigNode system. Could you please elaborate on the issue as it stands with this particular mod?

**Comment by Gerry1135** [comment]
I think he means that MM rebuilds its cache when any file that isn't in a PluginData folder is modified.  The settings should be moved into PluginData rather the Settings folder.

**Comment by CYBUTEK** [comment]
As expected, MM isn't indiscriminate in the files that it checks. It only checks the ones that are loaded and stored within the GameDatabase as configuration files for cache breaking changes.

https://github.com/sarbian/ModuleManager/blob/master/moduleManager.cs#L1001

**Comment by Gerry1135** [comment]
I did think it sounded a bit strange and I certainly haven't noticed it ignoring the cache (though I don't tend to run with a lot of MM patches unless I'm doing something RO/RSS related.  I presume you're pretty certain that none of the KER files get included though it wouldn't be hard to build a version of MM that dumps out the name of every file it checks just to be sure.

**Comment by Kerbas-ad-astra** [comment]
Module Manager already logs which files cause it to rebuild the cache (broken out by additions, changes, and deletions).  It wouldn't be bad to verify this experimentally, but I don't believe I've ever seen KER's (or any) XML files in the list.

**Comment by Galenmacil** [comment]
I think this issue is/was always resolved. It is clear that Module Manager ignore all files not ending in .CFG and those present in "plugindata". I believe this issue can be closed.

**Comment by CYBUTEK** [comment]
Thanks for the poke on closing this issue @Galenmacil.
