### ISSUE TITLE
KER is reporting true anomaly in radians instead of degrees.

### ISSUE THREAD

**Issue by Hydragyrum** [CYBUTEK/KerbalEngineer#99]
In the orbital section, true anomaly is being reported in radians as opposed to degrees.

The lightly edited attached file shows the issue.
![ker_bug](https://cloud.githubusercontent.com/assets/4928181/15456424/dc5dd3c0-206f-11e6-8277-9ddd95b002c0.png)

**Comment by dewiniaid** [comment]
I can confirm this as well.  In fact, I just came here to make the same report.

And at mean anomaly of 0 and 180 degrees, the values of all 3 anomalies should converge.
